/****** Object:  Table [dbo].[spc_D2Value]    Script Date: 1/3/2023 1:51:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[spc_D2Value](
	[SampleSize] [int] NOT NULL,
	[D2] [nchar](10) NULL,
 CONSTRAINT [PK_spc_D2Value] PRIMARY KEY CLUSTERED 
(
	[SampleSize] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


